on:
  push:
    branches:
      - main # Prepare new release on new changes to main

permissions:
  contents: write
  pull-requests: write

name: Prepare new release

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@45996ed1f6d02564a971a2fa1b5860e934307cf7 # v5.0.0
        with:
          token: ${{ secrets.GRADES_VIEW_SOLID_RELEASE_PLEASE }}

